version: '3.8'

services:
    api:
        build: ./api
        volumes:
            - ./api:/usr/src/app
        ports:
            - 5002:80
        depends_on: 
            - mongo
    
    mongo:
        image: 'mongo:4.4.0'