version: "3.8"

services:
    mongo:
        image: "mongo:4.4.0"
        ports:
            - "27017:27017"
    
    rabbitmq:
        image: "rabbitmq:3.8.8-management"
        ports:
            - "5672:5672"
            - "15672:15672"
    
    api:
        build: ./api
        volumes:
            - ./api:/usr/src/app
        ports:
            - "5002:80"
        depends_on: 
            - mongo
            - rabbitmq
        environment:
            RABBITMQ_AMQP_URL: "amqp://rabbitmq?connection_attempts=5&retry_delay=5"
            MONGO_DB_NAME: "notificationdb"

    worker:
        build: ./worker
        volumes:
            - ./worker:/usr/src/app
        ports: 
            - "5003:80"
        depends_on: 
            - mongo
            - rabbitmq
        environment:
            RABBITMQ_AMQP_URL: "amqp://rabbitmq?connection_attempts=5&retry_delay=5"
            MONGO_DB_NAME: "notificationdb"   
